/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package obj_mi_primera_aplicacion_cs;

import java.awt.Event;
import java.awt.event.KeyEvent;
import static java.lang.Integer.parseInt;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class Form_Factura extends javax.swing.JFrame {

    /**
     * Creates new form Form_Factura
     *
     * @throws java.sql.SQLException
     */
    ArrayList<Cliente_Beans> a_cl = new ArrayList<>();
    ArrayList<Empleado_Bens> a_em = new ArrayList<>();
    ArrayList<Producto_Beans> a_pt = new ArrayList<>();
    ImageIcon icono = new ImageIcon("src/Imagenes/Logo_4.png");

    public Form_Factura() throws SQLException {
        initComponents();
        this.setTitle("Love - Factura");
        this.setIconImage(icono.getImage());
        this.cliente_combo();
        this.cobrador_combo();
        this.id_factura();
        this.productos_lista();
        this.setLocationRelativeTo(null);
        this.Fecha_Actual();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jPanel2 = new javax.swing.JPanel();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbx_cliente = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cbx_cobrador = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbl_fecha = new javax.swing.JLabel();
        lbl_id_factura = new javax.swing.JLabel();
        lbl_telefono = new javax.swing.JLabel();
        lbl_direccion = new javax.swing.JLabel();
        lbl_cedula = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_productos = new javax.swing.JTable();
        bnt_cliente = new javax.swing.JButton();
        f_1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        chb_efectivo = new javax.swing.JCheckBox();
        chb_dinero_electronico = new javax.swing.JCheckBox();
        chb_tarjeta = new javax.swing.JCheckBox();
        chb_otros = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_descuento = new javax.swing.JTextField();
        txt_iva = new javax.swing.JTextField();
        txt_descuento_valor = new javax.swing.JTextField();
        txt_subtotal = new javax.swing.JTextField();
        txt_iva_valor = new javax.swing.JTextField();
        txt_total_factura = new javax.swing.JTextField();
        txt_efectivo = new javax.swing.JTextField();
        txt_cambio = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btn_terminar = new javax.swing.JButton();
        btn_producto = new javax.swing.JButton();
        btn_cobrador = new javax.swing.JButton();
        btn_volver = new javax.swing.JButton();
        btn_cliente = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btn_buscar = new javax.swing.JButton();
        lbl_titulo_cod_producto = new javax.swing.JLabel();
        lbl_cod_producto = new javax.swing.JLabel();
        lbl_titulo_pvp = new javax.swing.JLabel();
        lbl_pvp = new javax.swing.JLabel();
        lbl_fecha_elaboracion = new javax.swing.JLabel();
        lbl_titulo_fecha_elaboracion = new javax.swing.JLabel();
        lbl_titulo_fecha_vencimiento = new javax.swing.JLabel();
        lbl_fecha_vencimiento = new javax.swing.JLabel();
        txt_informacion_producto = new javax.swing.JTextField();
        btn_enviar = new javax.swing.JButton();
        txt_buscar_producto = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        list_lista_productos = new javax.swing.JList<>();
        lbl_titulo_productos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 212, 201));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setOpaque(false);

        jDesktopPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jDesktopPane2.setOpaque(false);
        jDesktopPane2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setBackground(new java.awt.Color(0, 204, 204));
        jScrollPane2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Cliente:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 60, 30));

        cbx_cliente.setBackground(new java.awt.Color(230, 230, 230));
        cbx_cliente.setEditable(true);
        cbx_cliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elige un cliente" }));
        cbx_cliente.setName(""); // NOI18N
        cbx_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_clienteActionPerformed(evt);
            }
        });
        cbx_cliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbx_clienteKeyPressed(evt);
            }
        });
        jPanel1.add(cbx_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 210, -1));

        jLabel2.setText("Cobrador:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 70, 30));

        cbx_cobrador.setBackground(new java.awt.Color(230, 230, 230));
        cbx_cobrador.setEditable(true);
        cbx_cobrador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elige un cobrador" }));
        jPanel1.add(cbx_cobrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 220, -1));

        jLabel3.setText("Fecha:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, -1, -1));

        jLabel4.setText("No");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        lbl_fecha.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.add(lbl_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 90, 20));

        lbl_id_factura.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.add(lbl_id_factura, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 100, 20));
        jPanel1.add(lbl_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 160, 60));
        jPanel1.add(lbl_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 290, 60));
        jPanel1.add(lbl_cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 160, 60));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 680, 60));

        tbl_productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre - Descripcion", "Cantidad", "Precio", "SubTotal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_productos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbl_productos.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                tbl_productosComponentAdded(evt);
            }
        });
        tbl_productos.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tbl_productosAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tbl_productos.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                tbl_productosInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        tbl_productos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbl_productosKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbl_productosKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_productos);
        if (tbl_productos.getColumnModel().getColumnCount() > 0) {
            tbl_productos.getColumnModel().getColumn(0).setMinWidth(40);
            tbl_productos.getColumnModel().getColumn(0).setMaxWidth(40);
            tbl_productos.getColumnModel().getColumn(1).setMinWidth(300);
            tbl_productos.getColumnModel().getColumn(1).setMaxWidth(300);
            tbl_productos.getColumnModel().getColumn(2).setMinWidth(70);
            tbl_productos.getColumnModel().getColumn(2).setMaxWidth(70);
        }

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 680, 100));

        bnt_cliente.setBackground(new java.awt.Color(230, 230, 230));
        bnt_cliente.setText("B");
        bnt_cliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bnt_cliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bnt_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt_clienteActionPerformed(evt);
            }
        });
        jPanel1.add(bnt_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 31, 25));

        jScrollPane2.setViewportView(jPanel1);

        jDesktopPane2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, 710, 280));

        f_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/op_2.jpg"))); // NOI18N
        jDesktopPane2.add(f_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 730, 300));

        jPanel6.setBackground(new java.awt.Color(35, 84, 97));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FORMA DE PAGO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(51, 51, 51))); // NOI18N

        chb_efectivo.setBackground(new java.awt.Color(255, 255, 255));
        chb_efectivo.setText("EFECTIVO");
        chb_efectivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chb_efectivoActionPerformed(evt);
            }
        });

        chb_dinero_electronico.setBackground(new java.awt.Color(255, 255, 255));
        chb_dinero_electronico.setText("DINERO ELECTRONICO");
        chb_dinero_electronico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chb_dinero_electronicoActionPerformed(evt);
            }
        });

        chb_tarjeta.setBackground(new java.awt.Color(255, 255, 255));
        chb_tarjeta.setText("TARJETA DE CREDITO/DEBITO");
        chb_tarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chb_tarjetaActionPerformed(evt);
            }
        });

        chb_otros.setBackground(new java.awt.Color(255, 255, 255));
        chb_otros.setText("OTROS");
        chb_otros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chb_otrosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chb_efectivo)
                    .addComponent(chb_dinero_electronico)
                    .addComponent(chb_tarjeta)
                    .addComponent(chb_otros))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(chb_efectivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chb_dinero_electronico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chb_tarjeta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chb_otros))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel8.setText("SUBTOTAL FACTURA");

        jLabel9.setText("DESCUENTO");

        jLabel10.setText("IVA");

        jLabel11.setText("TOTAL FACTURA");

        jLabel12.setText("%");

        jLabel13.setText("%");

        txt_descuento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_descuentoKeyPressed(evt);
            }
        });

        txt_iva.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_ivaKeyPressed(evt);
            }
        });

        txt_descuento_valor.setEditable(false);
        txt_descuento_valor.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txt_subtotal.setEditable(false);
        txt_subtotal.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txt_iva_valor.setEditable(false);
        txt_iva_valor.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_iva_valor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_iva_valorActionPerformed(evt);
            }
        });

        txt_total_factura.setEditable(false);
        txt_total_factura.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_total_factura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_total_facturaActionPerformed(evt);
            }
        });

        txt_efectivo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_efectivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_efectivoActionPerformed(evt);
            }
        });
        txt_efectivo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_efectivoKeyPressed(evt);
            }
        });

        txt_cambio.setEditable(false);
        txt_cambio.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_cambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cambioActionPerformed(evt);
            }
        });

        jLabel14.setText("EFECTIVO");

        jLabel15.setText("CAMBIO");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(187, Short.MAX_VALUE)
                .addComponent(txt_descuento_valor, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_iva, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_descuento, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel12)
                                .addComponent(jLabel13)))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(72, 72, 72)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_iva_valor, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_total_factura, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txt_efectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_cambio, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(txt_descuento_valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txt_iva_valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12)
                                .addComponent(txt_descuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_iva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_total_factura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(25, 25, 25)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_efectivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_cambio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        btn_terminar.setBackground(new java.awt.Color(230, 230, 230));
        btn_terminar.setText("Terminar");
        btn_terminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_terminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_terminarActionPerformed(evt);
            }
        });

        btn_producto.setBackground(new java.awt.Color(230, 230, 230));
        btn_producto.setText("Producto");
        btn_producto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_productoActionPerformed(evt);
            }
        });

        btn_cobrador.setBackground(new java.awt.Color(230, 230, 230));
        btn_cobrador.setText("Cobrador");
        btn_cobrador.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_cobrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cobradorActionPerformed(evt);
            }
        });

        btn_volver.setBackground(new java.awt.Color(230, 230, 230));
        btn_volver.setText("Menu");
        btn_volver.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_volverActionPerformed(evt);
            }
        });

        btn_cliente.setBackground(new java.awt.Color(230, 230, 230));
        btn_cliente.setText("Cliente");
        btn_cliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clienteActionPerformed(evt);
            }
        });

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel7.setFont(new java.awt.Font("Thames", 1, 24)); // NOI18N
        jLabel7.setText("Love");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel16.setText("Direccion:");

        jLabel17.setText("Av.Universitaria s/n y ");

        jLabel18.setText("Ramon Edulfo Cedeño M.");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel19.setText("Ruc:");

        jLabel20.setText("1310051766001");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel21.setText("Email:");

        jLabel22.setText("love69@gmail.com");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel18)
                    .addComponent(jLabel16)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("FACTURA");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Aut. SRI: 1130251486");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(btn_volver, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_cobrador, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_terminar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_terminar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cobrador, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_volver, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDesktopPane2))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_buscar.setBackground(new java.awt.Color(230, 230, 230));
        btn_buscar.setText("Buscar");
        btn_buscar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_buscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });
        jPanel3.add(btn_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 96, 33));

        lbl_titulo_cod_producto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(lbl_titulo_cod_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 150, 20));
        jPanel3.add(lbl_cod_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 480, 210, 20));

        lbl_titulo_pvp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(lbl_titulo_pvp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 180, 20));
        jPanel3.add(lbl_pvp, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 510, 180, 20));
        jPanel3.add(lbl_fecha_elaboracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 540, 210, 20));

        lbl_titulo_fecha_elaboracion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(lbl_titulo_fecha_elaboracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 150, 20));

        lbl_titulo_fecha_vencimiento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(lbl_titulo_fecha_vencimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, 160, 20));
        jPanel3.add(lbl_fecha_vencimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 570, 200, 20));

        txt_informacion_producto.setEditable(false);
        txt_informacion_producto.setBackground(new java.awt.Color(255, 255, 255));
        txt_informacion_producto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(txt_informacion_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 465, 389, 150));

        btn_enviar.setBackground(new java.awt.Color(230, 230, 230));
        btn_enviar.setText("Enviar");
        btn_enviar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_enviar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enviarActionPerformed(evt);
            }
        });
        jPanel3.add(btn_enviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 414, 95, 33));

        txt_buscar_producto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_buscar_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_buscar_productoActionPerformed(evt);
            }
        });
        txt_buscar_producto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_buscar_productoKeyPressed(evt);
            }
        });
        jPanel3.add(txt_buscar_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 258, 33));

        list_lista_productos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                list_lista_productosValueChanged(evt);
            }
        });
        jScrollPane5.setViewportView(list_lista_productos);

        jPanel3.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 87, 389, 320));

        lbl_titulo_productos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_titulo_productos.setText("Productos:");
        jPanel3.add(lbl_titulo_productos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 120, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_buscar_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_buscar_productoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_buscar_productoActionPerformed

    private void txt_iva_valorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_iva_valorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_iva_valorActionPerformed

    private void txt_total_facturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_total_facturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_total_facturaActionPerformed

    private void txt_efectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_efectivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_efectivoActionPerformed

    private void txt_cambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cambioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cambioActionPerformed

    private void cbx_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_clienteActionPerformed
        try {
            cliente_combo_items();
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_cbx_clienteActionPerformed

    private void cbx_clienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbx_clienteKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_cbx_clienteKeyPressed

    private void bnt_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt_clienteActionPerformed
        try {
            this.cliente_combo_buscar();
        } catch (SQLException ex) {
        }
    }//GEN-LAST:event_bnt_clienteActionPerformed

    private void list_lista_productosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_list_lista_productosValueChanged
        // TODO add your handling code here:
        if (!evt.getValueIsAdjusting()) {
            producto_informacion();
        }
    }//GEN-LAST:event_list_lista_productosValueChanged

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        // TODO add your handling code here:
        try {
            producto_buscar();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void btn_enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enviarActionPerformed
        // TODO add your handling code here:
        try {
            producto_enviar();
            producto_subtotal();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_enviarActionPerformed

    private void txt_buscar_productoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buscar_productoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                producto_buscar();
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_txt_buscar_productoKeyPressed

    private void tbl_productosComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_tbl_productosComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_productosComponentAdded

    private void tbl_productosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbl_productosKeyPressed

    }//GEN-LAST:event_tbl_productosKeyPressed

    private void tbl_productosAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tbl_productosAncestorAdded

    }//GEN-LAST:event_tbl_productosAncestorAdded

    private void tbl_productosInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_tbl_productosInputMethodTextChanged

    }//GEN-LAST:event_tbl_productosInputMethodTextChanged


    private void tbl_productosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbl_productosKeyReleased
        // TODO add your handling code here:
        try {
            producto_calcular();
            producto_subtotal();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_tbl_productosKeyReleased

    private void txt_descuentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_descuentoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                producto_subtotal();
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_txt_descuentoKeyPressed

    private void txt_ivaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ivaKeyPressed
        // TODO add your handling code here:
        try {
            producto_subtotal();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txt_ivaKeyPressed

    private void txt_efectivoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_efectivoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                double total = Double.parseDouble(txt_efectivo.getText()) - Double.parseDouble(txt_total_factura.getText());
                txt_cambio.setText("" + total);
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_txt_efectivoKeyPressed

    private void btn_terminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_terminarActionPerformed
        // TODO add your handling code here:
        registrar_factura();

    }//GEN-LAST:event_btn_terminarActionPerformed

    private void chb_efectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chb_efectivoActionPerformed
        // TODO add your handling code here:
        check_box_efectivo();
    }//GEN-LAST:event_chb_efectivoActionPerformed

    private void chb_dinero_electronicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chb_dinero_electronicoActionPerformed
        // TODO add your handling code here:
        check_box_dinero_electronico();
    }//GEN-LAST:event_chb_dinero_electronicoActionPerformed

    private void chb_tarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chb_tarjetaActionPerformed
        // TODO add your handling code here:
        check_box_tarjeta();
    }//GEN-LAST:event_chb_tarjetaActionPerformed

    private void chb_otrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chb_otrosActionPerformed
        // TODO add your handling code here:
        check_box_otros();
    }//GEN-LAST:event_chb_otrosActionPerformed

    private void btn_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_volverActionPerformed
        // TODO add your handling code here:
        try {
            Form_Menu m = new Form_Menu();
            m.setVisible(true);
            this.setVisible(false);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_volverActionPerformed

    private void btn_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clienteActionPerformed
        // TODO add your handling code here:
        try {
            Form_Cliente cl = new Form_Cliente();
            cl.setVisible(true);
            this.setVisible(false);
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_btn_clienteActionPerformed

    private void btn_cobradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cobradorActionPerformed
        // TODO add your handling code here:
        try {
            Form_Empleado em = new Form_Empleado();
            em.setVisible(true);
            this.setVisible(false);
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_btn_cobradorActionPerformed

    private void btn_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_productoActionPerformed
        // TODO add your handling code here:
        try {
            Form_Producto p = new Form_Producto();
            p.setVisible(true);
            this.setVisible(false);
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_btn_productoActionPerformed

    public void Fecha_Actual() {
        LocalDate fa = LocalDate.now();
        lbl_fecha.setText("   " + fa.toString());
    }

    public void id_factura() {
        try {
            Factura_Beans fc = new Factura_Beans();
            String x = "" + fc.Incremento_factura();
            lbl_id_factura.setText(x);
        } catch (Exception e) {
        }
    }

    public void cliente_combo() throws SQLException {
        try {
            Cliente_Beans cl = new Cliente_Beans();
            ResultSet rs = cl.Consultar_Tabla("select * from cliente;");
            int x = 1;
            while (rs.next()) {
                cbx_cliente.addItem(x + ". " + rs.getString("nombres") + " " + rs.getString("apellidos"));
                a_cl.add(new Cliente_Beans(parseInt(rs.getString("id_cliente")), rs.getString("cedula"), rs.getString("nombres"), rs.getString("apellidos"), rs.getString("direccion"), rs.getString("telefono")));
                x++;
            }
        } catch (Exception e) {

        }
    }

    public void cliente_combo_items() throws Exception {
        int i = cbx_cliente.getSelectedIndex();
        Cliente_Beans cl = new Cliente_Beans();
        ResultSet rs = cl.Consultar_Tabla("select cedula, telefono, direccion from cliente where id_cliente = " + a_cl.get(i - 1).getId_cliente() + ";");
        if (rs.next()) {
            lbl_cedula.setText("Cedula: " + rs.getString("cedula"));
            lbl_telefono.setText("Telefono: " + rs.getString("telefono"));
            lbl_direccion.setText("Direccion: " + rs.getString("direccion"));
        }
    }

    public void cliente_combo_buscar() throws SQLException {
        try {
            String texto_i = cbx_cliente.getSelectedItem().toString();
            int x = parseInt(texto_i);
            Cliente_Beans cl = new Cliente_Beans();
            ResultSet rs = cl.Consultar_Tabla("select cedula, telefono, direccion from cliente where id_cliente = " + texto_i + ";");
            if (rs.next()) {
                lbl_cedula.setText("Cedula: " + rs.getString("cedula"));
                lbl_telefono.setText("Telefono: " + rs.getString("telefono"));
                lbl_direccion.setText("Direccion: " + rs.getString("direccion"));
            }
            cbx_cliente.setSelectedItem(cbx_cliente.getItemAt(x));
        } catch (Exception e) {

        }
    }

    public void productos_lista() {
        try {
            Producto_Beans pt = new Producto_Beans();
            ResultSet rs = pt.Consultar_Tabla("select * from producto;");
            DefaultListModel modelo = new DefaultListModel();
            int x = 1;
            while (rs.next()) {
                modelo.addElement(x + ". " + rs.getString("nombre") + " - " + rs.getString("descripcion"));
                a_pt.add(new Producto_Beans(parseInt(rs.getString("id_producto")), rs.getString("cod_producto"), rs.getString("nombre"), rs.getString("descripcion"), Double.parseDouble(rs.getString("precio_costo")), Double.parseDouble(rs.getString("pvp")), parseInt(rs.getString("stock_maximo")), parseInt(rs.getString("stock_minimo")), rs.getString("fecha_elaboracion"), rs.getString("fecha_vencimiento")));
                x++;
            }
            list_lista_productos.setModel(modelo);
        } catch (Exception e) {

        }
    }

    public void producto_informacion() {
        try {
            int i = list_lista_productos.getSelectedIndex();
            Producto_Beans pt = new Producto_Beans();
            ResultSet rs = pt.Consultar_Tabla("select cod_producto, pvp, fecha_elaboracion, fecha_vencimiento from producto where id_producto = " + a_pt.get(i).getId_producto() + ";");
            if (rs.next()) {
                lbl_titulo_cod_producto.setText("Codigo del producto:");
                lbl_cod_producto.setText("" + rs.getString("cod_producto"));
                lbl_titulo_pvp.setText("Precio de venta al publico:");
                lbl_pvp.setText("" + rs.getString("pvp"));
                lbl_titulo_fecha_elaboracion.setText("Fecha de Elaboracion:");
                lbl_fecha_elaboracion.setText("" + rs.getString("fecha_elaboracion"));
                lbl_titulo_fecha_vencimiento.setText("Fecha de Vencimiento:");
                lbl_fecha_vencimiento.setText("" + rs.getString("fecha_vencimiento"));
            }
        } catch (Exception e) {

        }
    }

    public void producto_buscar() {
        try {
            Producto_Beans pt = new Producto_Beans();
            String i = txt_buscar_producto.getText();
            int x = 0;
            try {
                x = parseInt(i);
            } catch (Exception e) {
            }
            boolean f = true;
            ResultSet rs;
            for (int j = 0; j < a_pt.size(); j++) {
                if (x == a_pt.get(j).getId_producto()) {
                    rs = pt.Consultar_Tabla("select * from producto where id_producto = " + i + ";");
                    if (rs.next()) {
                        list_lista_productos.setSelectedIndex(j);
                        producto_informacion();
                    }
                    f = false;
                    break;
                } else if (i.equals(a_pt.get(j).getCod_producto())) {
                    rs = pt.Consultar_Tabla("select * from producto where id_producto = " + a_pt.get(j).getId_producto() + ";");
                    if (rs.next()) {
                        list_lista_productos.setSelectedIndex(j);
                        producto_informacion();
                    }
                    f = false;
                    break;
                }
            }
            if (f) {
                JOptionPane.showMessageDialog(null, "El producto no existe, asegúrese que el identificador sea correcto...");
            }
        } catch (Exception e) {

        }
    }

    public void producto_calcular() {
        try {
            int fila = tbl_productos.getSelectedRow();
            double sbt = Double.parseDouble(tbl_productos.getModel().getValueAt(fila, 2).toString());
            double sbt2 = Double.parseDouble(tbl_productos.getModel().getValueAt(fila, 3).toString());
            double total = sbt * sbt2;
            tbl_productos.setValueAt(total, fila, 4);
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }

    public int ultima_fila() {
        int fila = 0;
        for (int i = 0; i < tbl_productos.getRowCount(); i++) {
            if (tbl_productos.getValueAt(i, 0) == null) {
                fila = i;
                break;
            }
            fila = -1;
        }
        return fila;
    }

    public void producto_enviar() {
        try {
            if (ultima_fila() == -1) {
                DefaultTableModel modelo = (DefaultTableModel) tbl_productos.getModel();
                Object[] rowData = {null, null, null, null, null};
                modelo.addRow(rowData);

            }
            Producto_Beans pt = new Producto_Beans();
            int i = list_lista_productos.getSelectedIndex();
            ResultSet rs = pt.Consultar_Tabla("select * from producto where id_producto = " + a_pt.get(i).getId_producto() + ";");
            int fila = ultima_fila();
            if (rs.next()) {
                tbl_productos.setValueAt(rs.getString("id_producto"), fila, 0);
                tbl_productos.setValueAt(rs.getString("nombre") + " - " + rs.getString("descripcion"), fila, 1);
                tbl_productos.setValueAt(1, fila, 2);
                tbl_productos.setValueAt(Double.parseDouble(rs.getString("pvp")), fila, 3);
                double sbt = Double.parseDouble(tbl_productos.getModel().getValueAt(fila, 2).toString());
                double sbt2 = Double.parseDouble(tbl_productos.getModel().getValueAt(fila, 3).toString());
                double total = sbt * sbt2;
                tbl_productos.setValueAt(total, fila, 4);
            }
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }

    public void producto_subtotal() {
        try {
            double total = 0;
            for (int i = 0; i < tbl_productos.getRowCount(); i++) {
                if (tbl_productos.getValueAt(i, 4) != null) {
                    total = total + Double.parseDouble(tbl_productos.getValueAt(i, 4).toString());
                }
            }
            txt_subtotal.setText("" + total);
            if (!txt_descuento.getText().equals("")) {
                total = Double.parseDouble(txt_subtotal.getText()) - ((Double.parseDouble(txt_subtotal.getText()) * Double.parseDouble(txt_descuento.getText())) / 100);
                txt_descuento_valor.setText("" + total);
            } else {
                txt_descuento_valor.setText("");
            }

            if (!txt_descuento.getText().equals("") && !txt_iva.getText().equals("")) {
                total = Double.parseDouble(txt_descuento_valor.getText()) + ((Double.parseDouble(txt_descuento_valor.getText()) * Double.parseDouble(txt_iva.getText())) / 100);
                txt_iva_valor.setText("" + total);
            } else if (txt_descuento.getText().equals("") && !txt_iva.getText().equals("")) {
                total = Double.parseDouble(txt_subtotal.getText()) + ((Double.parseDouble(txt_subtotal.getText()) * Double.parseDouble(txt_iva.getText())) / 100);
                txt_iva_valor.setText("" + total);
            } else if (txt_iva.getText().equals("")) {
                txt_iva_valor.setText("");
            }

            if (!txt_iva.getText().equals("")) {
                txt_total_factura.setText(txt_iva_valor.getText());
            } else if (!txt_descuento.getText().equals("") && txt_iva.getText().equals("")) {
                txt_total_factura.setText(txt_descuento_valor.getText());
            } else if (txt_descuento.getText().equals("") && txt_iva.getText().equals("")) {
                txt_total_factura.setText(txt_subtotal.getText());
            }
        } catch (Exception e) {
        }
    }

    public void cobrador_combo() throws SQLException {
        try {
            Empleado_Bens em = new Empleado_Bens();
            ResultSet rs = em.Consultar_Tabla("select * from empleado;");
            int x = 1;
            while (rs.next()) {
                cbx_cobrador.addItem(x + ". " + rs.getString("nombres") + " " + rs.getString("apellidos"));
                a_em.add(new Empleado_Bens(parseInt(rs.getString("id_empleado")), rs.getString("nombres"), rs.getString("apellidos"), rs.getString("direccion"), rs.getString("telefono"), rs.getString("cargo")));
                x++;
            }
        } catch (Exception e) {

        }
    }

    public void check_box_efectivo() {
        if (chb_efectivo.isSelected()) {
            chb_dinero_electronico.setSelected(false);
            chb_tarjeta.setSelected(false);
            chb_otros.setSelected(false);
        }
    }

    public void check_box_dinero_electronico() {
        if (chb_dinero_electronico.isSelected()) {
            chb_tarjeta.setSelected(false);
            chb_otros.setSelected(false);
            chb_efectivo.setSelected(false);
        }
    }

    public void check_box_tarjeta() {
        if (chb_tarjeta.isSelected()) {
            chb_otros.setSelected(false);
            chb_efectivo.setSelected(false);
            chb_dinero_electronico.setSelected(false);
        }
    }

    public void check_box_otros() {
        if (chb_otros.isSelected()) {
            chb_efectivo.setSelected(false);
            chb_dinero_electronico.setSelected(false);
            chb_tarjeta.setSelected(false);
        }
    }

    public void registrar_factura() {
        try {
            Factura_Beans ft = new Factura_Beans();
            int i = cbx_cliente.getSelectedIndex();
            ft.setId_factura(parseInt(lbl_id_factura.getText()));
            ft.setId_cliente(a_cl.get(i - 1).getId_cliente());
            i = cbx_cobrador.getSelectedIndex();
            ft.setId_empleado(a_em.get(i - 1).getId_empleado());
            ft.setNumero(lbl_id_factura.getText());
            ft.setFecha(lbl_fecha.getText());
            ft.setSubtotal(Double.parseDouble(txt_subtotal.getText()));
            ft.setEfectivo(Double.parseDouble(txt_efectivo.getText()));
            ft.setCambio(Double.parseDouble(txt_cambio.getText()));
            if (txt_iva.getText().equals("")) {
                ft.setIva(0);
            } else {
                ft.setIva(Double.parseDouble(txt_iva.getText()));
            }
            if (txt_descuento.getText().equals("")) {
                ft.setDescuento(0);
            } else {
                ft.setDescuento(Double.parseDouble(txt_descuento.getText()));
            }
            ft.setTotal(Double.parseDouble(txt_total_factura.getText()));
            ft.Insertar_Factura();
            Detalle_Factura_Beans dft = new Detalle_Factura_Beans();
            for (int j = 0; j < tbl_productos.getRowCount(); j++) {
                if (tbl_productos.getValueAt(j, 0) == null) {
                    break;
                }
                dft.setId_detalle_factura(dft.Incremento_Detalle_factura());
                dft.setId_factura(parseInt(lbl_id_factura.getText()));
                dft.setId_producto(parseInt(tbl_productos.getValueAt(j, 0).toString()));
                dft.setCantidad(parseInt(tbl_productos.getValueAt(j, 2).toString()));
                dft.setPvp(Double.parseDouble(tbl_productos.getValueAt(j, 3).toString()));
                dft.setSubtotal(Double.parseDouble(tbl_productos.getValueAt(j, 4).toString()));
                if (chb_efectivo.isSelected()) {
                    dft.setForma_pago("Efectivo");
                } else if (chb_dinero_electronico.isSelected()) {
                    dft.setForma_pago("Dinero Electronico");
                } else if (chb_tarjeta.isSelected()) {
                    dft.setForma_pago("Tarjeta De Credito/Debito");
                } else {
                    dft.setForma_pago("Otros");
                }
                dft.Insertar_Detalle_factura();
            }
            Fecha_Actual();
            id_factura();
            cbx_cliente.setSelectedIndex(0);
            cbx_cobrador.setSelectedIndex(0);
            lbl_cedula.setText("");
            lbl_telefono.setText("");
            lbl_direccion.setText("");
            chb_dinero_electronico.setSelected(false);
            chb_efectivo.setSelected(false);
            chb_tarjeta.setSelected(false);
            chb_otros.setSelected(false);
            txt_cambio.setText("");
            txt_descuento.setText("");
            txt_descuento_valor.setText("");
            txt_efectivo.setText("");
            txt_iva.setText("");
            txt_iva_valor.setText("");
            txt_subtotal.setText("");
            txt_total_factura.setText("");
            for (int j = 0; j < tbl_productos.getRowCount(); j++) {
                tbl_productos.setValueAt(null, j, 0);
                tbl_productos.setValueAt(null, j, 1);
                tbl_productos.setValueAt(null, j, 2);
                tbl_productos.setValueAt(null, j, 3);
                tbl_productos.setValueAt(null, j, 4);
            }
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnt_cliente;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_cliente;
    private javax.swing.JButton btn_cobrador;
    private javax.swing.JButton btn_enviar;
    private javax.swing.JButton btn_producto;
    private javax.swing.JButton btn_terminar;
    private javax.swing.JButton btn_volver;
    private javax.swing.JComboBox<String> cbx_cliente;
    private javax.swing.JComboBox<String> cbx_cobrador;
    private javax.swing.JCheckBox chb_dinero_electronico;
    private javax.swing.JCheckBox chb_efectivo;
    private javax.swing.JCheckBox chb_otros;
    private javax.swing.JCheckBox chb_tarjeta;
    private javax.swing.JLabel f_1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lbl_cedula;
    private javax.swing.JLabel lbl_cod_producto;
    private javax.swing.JLabel lbl_direccion;
    private javax.swing.JLabel lbl_fecha;
    private javax.swing.JLabel lbl_fecha_elaboracion;
    private javax.swing.JLabel lbl_fecha_vencimiento;
    private javax.swing.JLabel lbl_id_factura;
    private javax.swing.JLabel lbl_pvp;
    private javax.swing.JLabel lbl_telefono;
    private javax.swing.JLabel lbl_titulo_cod_producto;
    private javax.swing.JLabel lbl_titulo_fecha_elaboracion;
    private javax.swing.JLabel lbl_titulo_fecha_vencimiento;
    private javax.swing.JLabel lbl_titulo_productos;
    private javax.swing.JLabel lbl_titulo_pvp;
    private javax.swing.JList<String> list_lista_productos;
    private javax.swing.JTable tbl_productos;
    private javax.swing.JTextField txt_buscar_producto;
    private javax.swing.JTextField txt_cambio;
    private javax.swing.JTextField txt_descuento;
    private javax.swing.JTextField txt_descuento_valor;
    private javax.swing.JTextField txt_efectivo;
    private javax.swing.JTextField txt_informacion_producto;
    private javax.swing.JTextField txt_iva;
    private javax.swing.JTextField txt_iva_valor;
    private javax.swing.JTextField txt_subtotal;
    private javax.swing.JTextField txt_total_factura;
    // End of variables declaration//GEN-END:variables
}
