package obj_mi_primera_aplicacion_cs;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;

public class Form_Producto extends javax.swing.JFrame {

    /**
     * Creates new form Form_Cliente
     */
    ImageIcon icono = new ImageIcon("src/Imagenes/Logo_4.png");
    boolean boolea = true;

    public Form_Producto() {
        initComponents();
        this.setIconImage(icono.getImage());
        this.setTitle("Love - Productos");
        this.setLocationRelativeTo(null);
        this.Mostar(tbl_producto, "select * from producto;");
        btn_cancelar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txt_mensaje = new javax.swing.JTextField();
        btn_nuevo = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_producto = new javax.swing.JTable();
        btn_enviar = new javax.swing.JButton();
        btn_actualizar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        btn_volver = new javax.swing.JButton();
        txt_fecha_vencimiento = new javax.swing.JTextField();
        lbl_fecha_vencimiento = new javax.swing.JLabel();
        lbl_fecha_elaboracion = new javax.swing.JLabel();
        lbl_stock_minimo = new javax.swing.JLabel();
        lbl_stock_maximo = new javax.swing.JLabel();
        lbl_pvp = new javax.swing.JLabel();
        lbl_precio_costo = new javax.swing.JLabel();
        lbl_descripcion = new javax.swing.JLabel();
        lbl_nombre = new javax.swing.JLabel();
        lbl_cod_producto = new javax.swing.JLabel();
        lbl_id_producto = new javax.swing.JLabel();
        txt_id_producto = new javax.swing.JTextField();
        txt_cod_producto = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        txt_descripcion = new javax.swing.JTextField();
        txt_precio = new javax.swing.JTextField();
        txt_pvp = new javax.swing.JTextField();
        txt_stock_maximo = new javax.swing.JTextField();
        txt_stock_minimo = new javax.swing.JTextField();
        txt_fecha_elaboracion = new javax.swing.JTextField();
        btn_factura = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(txt_mensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 440, 680, -1));

        btn_nuevo.setBackground(new java.awt.Color(230, 230, 230));
        btn_nuevo.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_nuevo.setText("Nuevo");
        btn_nuevo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_nuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoActionPerformed(evt);
            }
        });
        jPanel3.add(btn_nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, 108, -1));

        tbl_producto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "", "", "", "", "", "", "", "", "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_producto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_productoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_producto);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 480, 680, 115));

        btn_enviar.setBackground(new java.awt.Color(230, 230, 230));
        btn_enviar.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_enviar.setText("Enviar");
        btn_enviar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_enviar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enviarActionPerformed(evt);
            }
        });
        jPanel3.add(btn_enviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, 108, -1));

        btn_actualizar.setBackground(new java.awt.Color(230, 230, 230));
        btn_actualizar.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_actualizar.setText("Actualizar");
        btn_actualizar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_actualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarActionPerformed(evt);
            }
        });
        jPanel3.add(btn_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 210, 108, -1));

        btn_eliminar.setBackground(new java.awt.Color(230, 230, 230));
        btn_eliminar.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_eliminar.setText("Eliminar");
        btn_eliminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_eliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });
        jPanel3.add(btn_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 180, 108, -1));

        btn_cancelar.setBackground(new java.awt.Color(230, 230, 230));
        btn_cancelar.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_cancelar.setText("Cancelar");
        btn_cancelar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_cancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });
        jPanel3.add(btn_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, 108, -1));

        btn_volver.setBackground(new java.awt.Color(230, 230, 230));
        btn_volver.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_volver.setText("Menu");
        btn_volver.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_volver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_volverActionPerformed(evt);
            }
        });
        jPanel3.add(btn_volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, 108, -1));

        txt_fecha_vencimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_fecha_vencimientoActionPerformed(evt);
            }
        });
        jPanel3.add(txt_fecha_vencimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 359, -1));

        lbl_fecha_vencimiento.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lbl_fecha_vencimiento.setText("Fecha_Vencimiento");
        jPanel3.add(lbl_fecha_vencimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        lbl_fecha_elaboracion.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lbl_fecha_elaboracion.setText("Fecha_Elaboracion");
        jPanel3.add(lbl_fecha_elaboracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        lbl_stock_minimo.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lbl_stock_minimo.setText("Stock_Minimo");
        jPanel3.add(lbl_stock_minimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        lbl_stock_maximo.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lbl_stock_maximo.setText("Stock_Maximo");
        jPanel3.add(lbl_stock_maximo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        lbl_pvp.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lbl_pvp.setText("PVP");
        jPanel3.add(lbl_pvp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        lbl_precio_costo.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lbl_precio_costo.setText("Precio");
        jPanel3.add(lbl_precio_costo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        lbl_descripcion.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lbl_descripcion.setText("Descripcion");
        jPanel3.add(lbl_descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        lbl_nombre.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lbl_nombre.setText("Nombre");
        jPanel3.add(lbl_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        lbl_cod_producto.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lbl_cod_producto.setText("Cod_Producto");
        jPanel3.add(lbl_cod_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        lbl_id_producto.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lbl_id_producto.setText("Id_Poducto");
        jPanel3.add(lbl_id_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        txt_id_producto.setEditable(false);
        txt_id_producto.setBackground(new java.awt.Color(255, 255, 255));
        txt_id_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_id_productoActionPerformed(evt);
            }
        });
        jPanel3.add(txt_id_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 359, -1));
        jPanel3.add(txt_cod_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 359, -1));
        jPanel3.add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 359, -1));
        jPanel3.add(txt_descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 359, -1));
        jPanel3.add(txt_precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 359, -1));

        txt_pvp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pvpActionPerformed(evt);
            }
        });
        jPanel3.add(txt_pvp, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 359, -1));
        jPanel3.add(txt_stock_maximo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 359, -1));
        jPanel3.add(txt_stock_minimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 359, -1));
        jPanel3.add(txt_fecha_elaboracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 359, -1));

        btn_factura.setBackground(new java.awt.Color(230, 230, 230));
        btn_factura.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_factura.setText("Factura");
        btn_factura.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_factura.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_factura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_facturaActionPerformed(evt);
            }
        });
        jPanel3.add(btn_factura, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, 108, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 710, 610));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/op_2.1.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, -4, 750, 660));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_productoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_productoMouseClicked
        // TODO add your handling code here:
        //this.MouseClick();
    }//GEN-LAST:event_tbl_productoMouseClicked

    private void btn_enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enviarActionPerformed
        // TODO add your handling code here:
        this.Enviar();
    }//GEN-LAST:event_btn_enviarActionPerformed

    private void btn_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoActionPerformed
        // TODO add your handling code here:
        this.Nuevo();
    }//GEN-LAST:event_btn_nuevoActionPerformed

    private void btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarActionPerformed
        // TODO add your handling code here:
        actualizar();
    }//GEN-LAST:event_btn_actualizarActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        // TODO add your handling code here:
        cancelar();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_volverActionPerformed
        // TODO add your handling code here:
        try {
            Form_Menu m = new Form_Menu();
            m.setVisible(true);
            this.setVisible(false);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_volverActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        // TODO add your handling code here:
        eliminar();
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void txt_fecha_vencimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_fecha_vencimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_fecha_vencimientoActionPerformed

    private void txt_pvpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pvpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pvpActionPerformed

    private void btn_facturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_facturaActionPerformed
        // TODO add your handling code here:
        try {
            Form_Factura f = new Form_Factura();
            f.setVisible(true);
            this.setVisible(false);
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_btn_facturaActionPerformed

    private void txt_id_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_id_productoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_id_productoActionPerformed

    private void Nuevo() {
        try {
            Producto_Beans cb = new Producto_Beans();
            this.txt_id_producto.setText("" + cb.Incremento_Producto());
            this.txt_cod_producto.setText("");
            this.txt_nombre.setText("");
            this.txt_descripcion.setText("");
            this.txt_precio.setText("");
            this.txt_pvp.setText("");
            this.txt_stock_maximo.setText("");
            this.txt_stock_minimo.setText("");
            this.txt_fecha_elaboracion.setText("");
            this.txt_fecha_vencimiento.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error " + e.toString());
        }
    }

    private void Enviar() {
        try {
            Producto_Beans cb = new Producto_Beans();
            cb.setId_producto(Integer.parseInt(txt_id_producto.getText()));
            cb.setCod_producto(txt_cod_producto.getText());
            cb.setNombre(txt_nombre.getText());
            cb.setDescripcion(txt_descripcion.getText());
            cb.setPrecio_costo(Double.parseDouble(txt_precio.getText()));
            cb.setPvp(Double.parseDouble(txt_pvp.getText()));
            cb.setStock_maximo(Integer.parseInt(txt_stock_maximo.getText()));
            cb.setStock_minimo(Integer.parseInt(txt_stock_minimo.getText()));
            cb.setFecha_elaboracion(txt_fecha_elaboracion.getText());
            cb.setFecha_vencimiento(txt_fecha_vencimiento.getText());
            cb.Insertar_Producto();
            this.Mostar(tbl_producto, "select * from producto;");
            JOptionPane.showMessageDialog(null, "La informacion ha sido registrada con exito...");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error " + e.toString());
        }
    }

    private void Mostar(javax.swing.JTable jt, String sql) {
        try {
            Producto_Beans cb = new Producto_Beans();
            ResultSet rs;
            DefaultTableModel modelo = new DefaultTableModel();
            jt.setModel(modelo);
            rs = cb.Consultar_Tabla(sql);
            ResultSetMetaData rsmd;
            rsmd = rs.getMetaData();
            int cantcolumnas = rsmd.getColumnCount();
            for (int i = 1; i <= cantcolumnas; i++) {
                modelo.addColumn(rsmd.getColumnLabel(i));
            }
            while (rs.next()) {
                Object[] columna = new Object[cantcolumnas];
                for (int i = 0; i < cantcolumnas; i++) {
                    columna[i] = rs.getObject(i + 1);
                }
                modelo.addRow(columna);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error " + e.toString());
        }
    }

    private void MouseClick() {
        try {
            int fila = tbl_producto.getSelectedRow();
            System.out.println(fila);
            txt_id_producto.setText(tbl_producto.getModel().getValueAt(fila, 0).toString());
            txt_cod_producto.setText(tbl_producto.getModel().getValueAt(fila, 1).toString());
            txt_nombre.setText(tbl_producto.getModel().getValueAt(fila, 2).toString());
            txt_descripcion.setText(tbl_producto.getModel().getValueAt(fila, 3).toString());
            txt_precio.setText(tbl_producto.getModel().getValueAt(fila, 4).toString());
            txt_pvp.setText(tbl_producto.getModel().getValueAt(fila, 5).toString());
            txt_stock_maximo.setText(tbl_producto.getModel().getValueAt(fila, 6).toString());
            txt_stock_minimo.setText(tbl_producto.getModel().getValueAt(fila, 7).toString());
            txt_fecha_elaboracion.setText(tbl_producto.getModel().getValueAt(fila, 8).toString());
            txt_fecha_vencimiento.setText(tbl_producto.getModel().getValueAt(fila, 9).toString());
        } catch (Exception e) {
        }
    }

    public void actualizar() {
        try {
            Producto_Beans pd = new Producto_Beans();
            if (boolea) {
                String texto = JOptionPane.showInputDialog("Ingrese el identificador del producto que quiere actualizar: ");
                ResultSet rs = pd.Consultar_Tabla("select * from producto where id_producto = " + texto + ";");
                if (rs.next()) {
                    btn_factura.setEnabled(false);
                    btn_volver.setEnabled(false);
                    btn_eliminar.setEnabled(false);
                    btn_enviar.setEnabled(false);
                    btn_nuevo.setEnabled(false);
                    txt_id_producto.setText(rs.getString("id_producto"));
                    txt_nombre.setText(rs.getString("nombre"));
                    txt_cod_producto.setText(rs.getString("cod_producto"));
                    txt_descripcion.setText(rs.getString("descripcion"));
                    txt_precio.setText(rs.getString("precio_costo"));
                    txt_pvp.setText(rs.getString("pvp"));
                    txt_stock_maximo.setText(rs.getString("stock_maximo"));
                    txt_stock_minimo.setText(rs.getString("stock_minimo"));
                    txt_fecha_elaboracion.setText(rs.getString("fecha_elaboracion"));
                    txt_fecha_vencimiento.setText(rs.getString("fecha_vencimiento"));
                    JOptionPane.showMessageDialog(null, "Modifique los datos que quiere actualizar...");
                    txt_mensaje.setText("Modifique los datos que quiere actualizar...");
                    boolea = false;
                    btn_cancelar.setEnabled(true);
                }
            } else {
                pd.Actualizar_Producto(Integer.parseInt(txt_id_producto.getText()), txt_cod_producto.getText(), txt_nombre.getText(), txt_descripcion.getText(), Double.parseDouble(txt_precio.getText()), Double.parseDouble(txt_pvp.getText()), Integer.parseInt(txt_stock_maximo.getText()), Integer.parseInt(txt_stock_minimo.getText()), txt_fecha_elaboracion.getText(), txt_fecha_vencimiento.getText());
                btn_factura.setEnabled(true);
                btn_eliminar.setEnabled(true);
                btn_volver.setEnabled(true);
                btn_enviar.setEnabled(true);
                btn_nuevo.setEnabled(true);
                txt_id_producto.setText("" + pd.Incremento_Producto());
                txt_nombre.setText("");
                txt_cod_producto.setText("");
                txt_descripcion.setText("");
                txt_precio.setText("");
                txt_pvp.setText("");
                txt_stock_maximo.setText("");
                txt_stock_minimo.setText("");
                txt_fecha_elaboracion.setText("");
                txt_fecha_vencimiento.setText("");
                txt_mensaje.setText("");
                boolea = true;
                this.Mostar(tbl_producto, "select * from producto;");
                btn_cancelar.setEnabled(false);
            }
        } catch (Exception e) {
        }
    }

    public void cancelar() {
        try {
            Producto_Beans pd = new Producto_Beans();
            txt_id_producto.setText("" + pd.Incremento_Producto());
            txt_nombre.setText("");
            txt_cod_producto.setText("");
            txt_descripcion.setText("");
            txt_precio.setText("");
            txt_pvp.setText("");
            txt_stock_maximo.setText("");
            txt_stock_minimo.setText("");
            txt_fecha_elaboracion.setText("");
            txt_fecha_vencimiento.setText("");
            txt_mensaje.setText("");
            btn_actualizar.setEnabled(true);
            btn_factura.setEnabled(true);
            btn_eliminar.setEnabled(true);
            btn_enviar.setEnabled(true);
            btn_nuevo.setEnabled(true);
            btn_volver.setEnabled(true);
            btn_cancelar.setEnabled(false);
            boolea = true;
        } catch (Exception ex) {
        }
    }

    public void eliminar() {
        try {
            Producto_Beans pd = new Producto_Beans();
            if (boolea) {
                String texto = JOptionPane.showInputDialog("Ingrese el identificador del producto que quiere eliminar: ");
                ResultSet rs = pd.Consultar_Tabla("select * from producto where id_producto = " + texto + ";");
                if (rs.next()) {
                    btn_factura.setEnabled(false);
                    btn_volver.setEnabled(false);
                    btn_actualizar.setEnabled(false);
                    btn_enviar.setEnabled(false);
                    btn_nuevo.setEnabled(false);
                    txt_id_producto.setText(rs.getString("id_producto"));
                    txt_nombre.setText(rs.getString("nombre"));
                    txt_cod_producto.setText(rs.getString("cod_producto"));
                    txt_descripcion.setText(rs.getString("descripcion"));
                    txt_precio.setText(rs.getString("precio_costo"));
                    txt_pvp.setText(rs.getString("pvp"));
                    txt_stock_maximo.setText(rs.getString("stock_maximo"));
                    txt_stock_minimo.setText(rs.getString("stock_minimo"));
                    txt_fecha_elaboracion.setText(rs.getString("fecha_elaboracion"));
                    txt_fecha_vencimiento.setText(rs.getString("fecha_vencimiento"));
                    JOptionPane.showMessageDialog(null, "Esta es el producto que desea eliminar...");
                    txt_mensaje.setText("Esta es el producto que desea eliminar...");
                    boolea = false;
                    btn_cancelar.setEnabled(true);
                }
            } else {
                pd.Eliminar_Producto(Integer.parseInt(txt_id_producto.getText()));
                btn_factura.setEnabled(true);
                btn_volver.setEnabled(true);
                btn_actualizar.setEnabled(true);
                btn_enviar.setEnabled(true);
                btn_nuevo.setEnabled(true);
                txt_id_producto.setText("" + pd.Incremento_Producto());
                txt_nombre.setText("");
                txt_cod_producto.setText("");
                txt_descripcion.setText("");
                txt_precio.setText("");
                txt_pvp.setText("");
                txt_stock_maximo.setText("");
                txt_stock_minimo.setText("");
                txt_fecha_elaboracion.setText("");
                txt_fecha_vencimiento.setText("");
                txt_mensaje.setText("");
                boolea = true;
                this.Mostar(tbl_producto, "select * from producto;");
                btn_cancelar.setEnabled(false);
            }
        } catch (Exception ex) {
        }
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_actualizar;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_enviar;
    private javax.swing.JButton btn_factura;
    private javax.swing.JButton btn_nuevo;
    private javax.swing.JButton btn_volver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_cod_producto;
    private javax.swing.JLabel lbl_descripcion;
    private javax.swing.JLabel lbl_fecha_elaboracion;
    private javax.swing.JLabel lbl_fecha_vencimiento;
    private javax.swing.JLabel lbl_id_producto;
    private javax.swing.JLabel lbl_nombre;
    private javax.swing.JLabel lbl_precio_costo;
    private javax.swing.JLabel lbl_pvp;
    private javax.swing.JLabel lbl_stock_maximo;
    private javax.swing.JLabel lbl_stock_minimo;
    private javax.swing.JTable tbl_producto;
    private javax.swing.JTextField txt_cod_producto;
    private javax.swing.JTextField txt_descripcion;
    private javax.swing.JTextField txt_fecha_elaboracion;
    private javax.swing.JTextField txt_fecha_vencimiento;
    private javax.swing.JTextField txt_id_producto;
    private javax.swing.JTextField txt_mensaje;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_precio;
    private javax.swing.JTextField txt_pvp;
    private javax.swing.JTextField txt_stock_maximo;
    private javax.swing.JTextField txt_stock_minimo;
    // End of variables declaration//GEN-END:variables
}
