/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package obj_mi_primera_aplicacion_cs;

import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class Form_Cliente extends javax.swing.JFrame {

    /**
     * Creates new form Form_Cliente
     */
    ImageIcon icono = new ImageIcon("src/Imagenes/Logo_4.png");
    boolean boolea = true;

    public Form_Cliente() {
        initComponents();
        this.setIconImage(icono.getImage());
        this.setTitle("Love - Clientes");
        this.setLocationRelativeTo(null);
        this.Mostar(tbl_cliente, "select * from cliente;");
        btn_cancelar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txt_mensaje = new javax.swing.JTextField();
        btn_nuevo = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_cliente = new javax.swing.JTable();
        btn_enviar = new javax.swing.JButton();
        btn_actualizar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        btn_volver = new javax.swing.JButton();
        lbl_id_cliente = new javax.swing.JLabel();
        lbl_cedula = new javax.swing.JLabel();
        lbl_nombres = new javax.swing.JLabel();
        lbl_apellidos = new javax.swing.JLabel();
        lbl_direccion = new javax.swing.JLabel();
        lbl_telefono = new javax.swing.JLabel();
        txt_telefono = new javax.swing.JTextField();
        txt_direccion = new javax.swing.JTextField();
        txt_apellidos = new javax.swing.JTextField();
        txt_nombres = new javax.swing.JTextField();
        txt_cedula = new javax.swing.JTextField();
        txt_id_cliente = new javax.swing.JTextField();
        btn_factura = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btn_nuevo.setBackground(new java.awt.Color(230, 230, 230));
        btn_nuevo.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_nuevo.setText("Nuevo");
        btn_nuevo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_nuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoActionPerformed(evt);
            }
        });

        tbl_cliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "", "", "", "", "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_clienteMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_cliente);

        btn_enviar.setBackground(new java.awt.Color(230, 230, 230));
        btn_enviar.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_enviar.setText("Enviar");
        btn_enviar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_enviar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enviarActionPerformed(evt);
            }
        });

        btn_actualizar.setBackground(new java.awt.Color(230, 230, 230));
        btn_actualizar.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_actualizar.setText("Actualizar");
        btn_actualizar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_actualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarActionPerformed(evt);
            }
        });

        btn_eliminar.setBackground(new java.awt.Color(230, 230, 230));
        btn_eliminar.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_eliminar.setText("Eliminar");
        btn_eliminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_eliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        btn_cancelar.setBackground(new java.awt.Color(230, 230, 230));
        btn_cancelar.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_cancelar.setText("Cancelar");
        btn_cancelar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_cancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        btn_volver.setBackground(new java.awt.Color(230, 230, 230));
        btn_volver.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_volver.setText("Menu");
        btn_volver.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_volver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_volverActionPerformed(evt);
            }
        });

        lbl_id_cliente.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lbl_id_cliente.setText("Id_Cliente");

        lbl_cedula.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lbl_cedula.setText("Cedula");

        lbl_nombres.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lbl_nombres.setText("Nombres");

        lbl_apellidos.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lbl_apellidos.setText("Apellidos");

        lbl_direccion.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lbl_direccion.setText("Direccion");

        lbl_telefono.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lbl_telefono.setText("Telefono");

        txt_telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_telefonoActionPerformed(evt);
            }
        });

        txt_id_cliente.setEditable(false);
        txt_id_cliente.setBackground(new java.awt.Color(255, 255, 255));

        btn_factura.setBackground(new java.awt.Color(230, 230, 230));
        btn_factura.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_factura.setText("Factura");
        btn_factura.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_factura.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_factura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_facturaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_cedula)
                            .addComponent(lbl_nombres)
                            .addComponent(lbl_apellidos)
                            .addComponent(lbl_direccion)
                            .addComponent(lbl_telefono)
                            .addComponent(lbl_id_cliente))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_telefono)
                            .addComponent(txt_direccion)
                            .addComponent(txt_nombres)
                            .addComponent(txt_apellidos)
                            .addComponent(txt_id_cliente)
                            .addComponent(txt_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_volver, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btn_cancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btn_nuevo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(btn_actualizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_eliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_enviar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btn_factura, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btn_volver)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_factura)
                        .addGap(28, 28, 28)
                        .addComponent(btn_nuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_enviar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_eliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_actualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_cancelar))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_id_cliente)
                            .addComponent(txt_id_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_cedula)
                            .addComponent(txt_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_nombres)
                            .addComponent(txt_nombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_apellidos)
                            .addComponent(txt_apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_direccion)
                            .addComponent(txt_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_telefono)
                            .addComponent(txt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(txt_mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 710, 440));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/op_2.1.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, -4, 750, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoActionPerformed
        // TODO add your handling code here:
        if (txt_id_cliente.getText().equals("")) {
            this.Nuevo();
        }
    }//GEN-LAST:event_btn_nuevoActionPerformed

    private void tbl_clienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_clienteMouseClicked
        // TODO add your handling code here:
        //this.MouseClick();
    }//GEN-LAST:event_tbl_clienteMouseClicked

    private void btn_enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enviarActionPerformed
        // TODO add your handling code here:
        this.Enviar();
    }//GEN-LAST:event_btn_enviarActionPerformed

    private void btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarActionPerformed
        // TODO add your handling code here:
        actualizar();
    }//GEN-LAST:event_btn_actualizarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        // TODO add your handling code here:
        eliminar();
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        // TODO add your handling code here:
        cancelar();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_volverActionPerformed
        // TODO add your handling code here:
        try {
            Form_Menu m = new Form_Menu();
            m.setVisible(true);
            this.setVisible(false);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_volverActionPerformed

    private void txt_telefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_telefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_telefonoActionPerformed

    private void btn_facturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_facturaActionPerformed
        // TODO add your handling code here:
        try {
            Form_Factura f = new Form_Factura();
            f.setVisible(true);
            this.setVisible(false);
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_btn_facturaActionPerformed

    private void Nuevo() {
        try {
            Cliente_Beans cb = new Cliente_Beans();       //ta
            Texto_2(cb);                                  //ta
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error " + e.toString());
        }
        //TME = 2ta
        //TPE = 2ta
        //TPR = (2ta + 2ta) / 2
        //TPR = 2ta
    }

    private void Enviar() {
        try {
            Cliente_Beans cb = new Cliente_Beans();
            cb.setId_cliente(Integer.parseInt(txt_id_cliente.getText()));         //ta
            cb.setCedula(txt_cedula.getText());                                   //ta
            cb.setNombres(txt_nombres.getText());                                 //ta
            cb.setApellidos(txt_apellidos.getText());                             //ta  
            cb.setDireccion(txt_direccion.getText());                             //ta
            cb.setTelefono(txt_telefono.getText());                               //ta
            cb.Insertar_Cliente();                                                
            this.Mostar(tbl_cliente, "select * from cliente;");
            JOptionPane.showMessageDialog(null, "La informacion ha sido registrada con exito...");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error " + e.toString());
        }
        //TME = 6ta
        //TPE = 6ta
        //TPR = (6ta + 6ta) / 2
        //TPR = 6ta
    }

    private void Mostar(javax.swing.JTable jt, String sql) {
        try {
            Cliente_Beans cb = new Cliente_Beans();               //ta
            ResultSet rs;
            DefaultTableModel modelo = new DefaultTableModel();   //ta
            jt.setModel(modelo);                                  //ta
            rs = cb.Consultar_Tabla(sql);                         //ta
            ResultSetMetaData rsmd;
            rsmd = rs.getMetaData();                              //ta
            int cantcolumnas = rsmd.getColumnCount();             //ta
            for (int i = 1; i <= cantcolumnas; i++) {             //(cantcolumnas)*tc + (cantcolumnas)*ta + (cantcolumnas)*to + ta + tc
                modelo.addColumn(rsmd.getColumnLabel(i));         //¿?(cantcolumnas)(ta)
            }
            while (rs.next()) {                                   //(rs.next())tc + tc
                Object[] columna = new Object[cantcolumnas];      //¿?(rs.next())(ta)
                for (int i = 0; i < cantcolumnas; i++) {          //¿?(rs.next())((cantcolumnas)*tc + (cantcolumnas)*ta + (cantcolumnas)*to + ta + tc))
                    columna[i] = rs.getObject(i + 1);             //¿?(rs.next())(ta+to)
                }
                modelo.addRow(columna);                           //¿?(rs.next())(ta)
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error " + e.toString());
        }
        //TME = (cantcolumnas)*tc + (cantcolumnas)*ta + (cantcolumnas)*to + (rs.next())tc + 7ta + 2tc
        //TPE = (cantcolumnas)*tc + (cantcolumnas)*ta + (cantcolumnas)*to + (rs.next())((cantcolumnas)*tc + (cantcolumnas)*ta + (cantcolumnas)*to + ta + tc)) + 2((rs.next())(ta)) + (rs.next())(ta+to) + (rs.next())tc + 7ta + 2tc
        //TPR = (((cantcolumnas)*tc + (cantcolumnas)*ta + (cantcolumnas)*to + (rs.next())tc + 7ta + 2tc)+((cantcolumnas)*tc + (cantcolumnas)*ta + (cantcolumnas)*to + (rs.next())((cantcolumnas)*tc + (cantcolumnas)*ta + (cantcolumnas)*to + ta + tc)) + 2((rs.next())(ta)) + (rs.next())(ta+to) + (rs.next())tc + 7ta + 2tc)) / 2
    }

    public void botones(boolean x) {
        btn_factura.setEnabled(x);   // Ta
        btn_volver.setEnabled(x);    // Ta
        btn_eliminar.setEnabled(x);  // Ta
        btn_enviar.setEnabled(x);    // Ta
        btn_nuevo.setEnabled(x);     // Ta
        //TME = Ta * 5
        //TPE = Ta * 5
        //TPR = (Ta * 5 + Ta * 5) / 2
        //TPR = 5 * Ta
    }

    public void botones_2(boolean x) {
        btn_factura.setEnabled(x);    // Ta
        btn_volver.setEnabled(x);     // Ta
        btn_actualizar.setEnabled(x); // Ta
        btn_enviar.setEnabled(x);     // Ta
        btn_nuevo.setEnabled(x);      // Ta
        //TME = Ta * 5
        //TPE = Ta * 5
        //TPR = (Ta * 5 + Ta * 5) / 2
        //TPR = 5 * Ta
    }

    public void Texto(ResultSet rs) {
        try {
            txt_id_cliente.setText(rs.getString("id_cliente"));      // Ta + To
            txt_nombres.setText(rs.getString("nombres"));            // Ta + To
            txt_apellidos.setText(rs.getString("apellidos"));        // Ta + To
            txt_direccion.setText(rs.getString("direccion"));        // Ta + To
            txt_cedula.setText(rs.getString("cedula"));              // Ta + To
            txt_telefono.setText(rs.getString("telefono"));          // Ta + To
            //TME = (Ta + To) * 6
            //TPE = (Ta + To) * 6
            //TPR = (((Ta + To) * 6)+((Ta + To) * 6)) / 2
            //TPR = (Ta + To) * 6
        } catch (Exception e) {
        }
    }

    public void Texto_2(Cliente_Beans cl) {
        try {
            txt_id_cliente.setText("" + cl.Incremento_Cliente());  // Ta + To
            txt_nombres.setText("");                                // Ta
            txt_apellidos.setText("");                              // Ta
            txt_direccion.setText("");                              // Ta
            txt_cedula.setText("");                                 // Ta
            txt_telefono.setText("");                               // Ta
            txt_mensaje.setText("");                                // Ta
            //TME = 7Ta + To
            //TPE = 7Ta + To
            //TPR = ((7Ta + To)+(7Ta + To)) / 2
            //TPR = 7Ta + To
        } catch (Exception e) {
        }
    }

    public void actualizar() {
        try {
            Cliente_Beans cl = new Cliente_Beans(); //ta
            if (boolea) { //tc
                String texto = JOptionPane.showInputDialog("Ingrese el identificador del cliente que quiere actualizar: "); //¿? ta
                ResultSet rs = cl.Consultar_Tabla("select * from cliente where id_cliente = " + texto + ";"); //¿? ta
                if (rs.next()) { //¿? tc
                    botones(false); //¿? ta
                    Texto(rs); //¿? ta  
                    JOptionPane.showMessageDialog(null, "Modifique los datos que quiere actualizar...");
                    txt_mensaje.setText("Modifique los datos que quiere actualizar...");
                    boolea = false; //¿? ta
                    btn_cancelar.setEnabled(true); //¿? ta
                }
            } else {
                cl.Actualizar_Cliente(Integer.parseInt(txt_id_cliente.getText()), txt_cedula.getText(), txt_nombres.getText(), txt_apellidos.getText(), txt_direccion.getText(), txt_telefono.getText()); //¿? ta
                botones(true); //¿? ta
                Texto_2(cl); //¿? ta
                boolea = true; //¿? ta
                this.Mostar(tbl_cliente, "select * from cliente;"); //¿? ta 
                btn_cancelar.setEnabled(false); //¿? ta 
            }                                                                                                                  
        } catch (Exception e) {
        }
        //TME = ta + tc
        //TPE = 13ta + 3tc
        //TPR = ((ta + tc)+(13ta+ 2tc))/2
        //TPR = 7ta + 2tc
    }

    public void cancelar() {
        try {
            Cliente_Beans cl = new Cliente_Beans();  // ta
            Texto_2(cl);                             // ta 
            botones(true);                           // ta
            btn_actualizar.setEnabled(true);         // ta
            btn_cancelar.setEnabled(false);          // ta  
            boolea = true;                           // ta
        } catch (Exception ex) {
        }
        //TME = 6ta
        //TPE = 6ta
        //TPR = (6ta + 6ta)/2
        //TPR = 6ta
    }

    public void eliminar() {
        try {
            Cliente_Beans cl = new Cliente_Beans(); // ta
            if (boolea) { // tc
                String texto = JOptionPane.showInputDialog("Ingrese el identificador del cliente que quiere Eliminar: "); //¿? ta
                ResultSet rs = cl.Consultar_Tabla("select * from cliente where id_cliente = " + texto + ";"); //¿? ta
                if (rs.next()) { //¿? tc
                    botones_2(false); //¿? ta
                    Texto(rs); //¿? ta
                    JOptionPane.showMessageDialog(null, "Esta es el cliente que desea eliminar...");
                    txt_mensaje.setText("Esta es el cliente que desea eliminar..."); //¿? ta
                    boolea = false; //¿? ta  
                    btn_cancelar.setEnabled(true); //¿? ta
                }
            } else {
                cl.Eliminar_Cliente(Integer.parseInt(txt_id_cliente.getText())); //¿? ta
                botones_2(true); //¿? ta
                Texto_2(cl); //¿? ta
                boolea = true; //¿? ta
                this.Mostar(tbl_cliente, "select * from cliente;");
                btn_cancelar.setEnabled(false); //¿? ta
            }                                                                                                              
        } catch (Exception ex) {
        }
        //TME = ta + tc
        //TPE = 13ta + 3tc
        //TPR = ((ta + tc)+(13ta + 3tc))/2
        //TPR = 7ta + 2tc
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_actualizar;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_enviar;
    private javax.swing.JButton btn_factura;
    private javax.swing.JButton btn_nuevo;
    private javax.swing.JButton btn_volver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_apellidos;
    private javax.swing.JLabel lbl_cedula;
    private javax.swing.JLabel lbl_direccion;
    private javax.swing.JLabel lbl_id_cliente;
    private javax.swing.JLabel lbl_nombres;
    private javax.swing.JLabel lbl_telefono;
    private javax.swing.JTable tbl_cliente;
    private javax.swing.JTextField txt_apellidos;
    private javax.swing.JTextField txt_cedula;
    private javax.swing.JTextField txt_direccion;
    private javax.swing.JTextField txt_id_cliente;
    private javax.swing.JTextField txt_mensaje;
    private javax.swing.JTextField txt_nombres;
    private javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables
}
